package vo;
// Generated 2016-9-4 15:59:52 by Hibernate Tools 3.5.0.Final

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private String userPwd;
	private Integer gender;
	private byte[] picture;
	private String email;
	private String phoneNum;
	private String address;

	public UserInfo() {
	}

	public UserInfo(String userName, String userPwd, Integer gender, byte[] picture, String email, String phoneNum,
			String address) {
		this.userName = userName;
		this.userPwd = userPwd;
		this.gender = gender;
		this.picture = picture;
		this.email = email;
		this.phoneNum = phoneNum;
		this.address = address;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPwd() {
		return this.userPwd;
	}

	public void setUserPwd(String userPwd) {
		this.userPwd = userPwd;
	}

	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	public byte[] getPicture() {
		return this.picture;
	}

	public void setPicture(byte[] picture) {
		this.picture = picture;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhoneNum() {
		return this.phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
